package imp

const OPEN_BLOCK_GROUPING = "{"
const CLOSE_BLOCK_GROUPING = "}"
const PRINT = "print"
const WHILE = "while"
const IF = "if"
const ELSE = "else"
const STATEMENT_DELIMITER = ";"
const DECLARATION = ":="
const ASSIGNMENT = "="
const ADD = "+"
const MULTIPLY = "*"
const OR = "||"
const AND = "&&"
const NOT = "!"
const EQUALS = "=="
const LESS_THAN = "<"
const OPEN_EXPRESSION_GROUPING = "("
const CLOSE_EXPRESSION_GROUPING = ")"
const BOOLEAN_TRUE = "true"
const BOOLEAN_FALSE = "false"
